# Activation function testing

In [ ]:
import numpy as np
from layers.activation_functions import ReLU, Sigmoid

In [3]:
import numpy as np

Z = np.array([
    [-2.0, -1.0, 0.0, 1.0, 2.0],
    [ 3.0, -3.0, 0.5, -0.5, 0.0]
])

dA = np.ones_like(Z)   # upstream gradient = 1 everywhere


In [4]:
relu = ReLU()

A_relu = relu.forward(Z)
dZ_relu = relu.backward(dA)

print("ReLU forward:")
print(A_relu)

print("\nReLU backward:")
print(dZ_relu)


ReLU forward:
[[0.  0.  0.  1.  2. ]
 [3.  0.  0.5 0.  0. ]]

ReLU backward:
[[0. 0. 0. 1. 1.]
 [1. 0. 1. 0. 0.]]


In [5]:
sigmoid = Sigmoid()

A_sig = sigmoid.forward(Z)
dZ_sig = sigmoid.backward(dA)

print("\nSigmoid forward:")
print(A_sig)

print("\nSigmoid backward:")
print(dZ_sig)



Sigmoid forward:
[[0.11920292 0.26894142 0.5        0.73105858 0.88079708]
 [0.95257413 0.04742587 0.62245933 0.37754067 0.5       ]]

Sigmoid backward:
[[0.10499359 0.19661193 0.25       0.19661193 0.10499359]
 [0.04517666 0.04517666 0.23500371 0.23500371 0.25      ]]


## Mock Neural Network
Forward pass we perform: $$A^{[0]} = X \leftarrow \text{input layer}\\
Z^{[1]} = W^{[1]}A^{[0]} + b^{[1]} \\ 
A^{[1]} = g[Z^{[1]}] = \text{ReLU}(Z^{[1]}) \vee \text{Sigmoid}(Z^{[1]}) \\
Z^{[2]} = W^{[2]}A^{[1]} + b^{[2]} \\
A^{[2]} = \text{Softmax}(Z^{[2]})$$