# Activation function testing

In [2]:
import numpy as np
from layers.activation_functions import ReLU, Sigmoid

In [3]:
import numpy as np

Z = np.array([
    [-2.0, -1.0, 0.0, 1.0, 2.0],
    [ 3.0, -3.0, 0.5, -0.5, 0.0]
])

dA = np.ones_like(Z)   # upstream gradient = 1 everywhere


In [4]:
relu = ReLU()

A_relu = relu.forward(Z)
dZ_relu = relu.backward(dA)

print("ReLU forward:")
print(A_relu)

print("\nReLU backward:")
print(dZ_relu)


ReLU forward:
[[0.  0.  0.  1.  2. ]
 [3.  0.  0.5 0.  0. ]]

ReLU backward:
[[0. 0. 0. 1. 1.]
 [1. 0. 1. 0. 0.]]


In [5]:
sigmoid = Sigmoid()

A_sig = sigmoid.forward(Z)
dZ_sig = sigmoid.backward(dA)

print("\nSigmoid forward:")
print(A_sig)

print("\nSigmoid backward:")
print(dZ_sig)



Sigmoid forward:
[[0.11920292 0.26894142 0.5        0.73105858 0.88079708]
 [0.95257413 0.04742587 0.62245933 0.37754067 0.5       ]]

Sigmoid backward:
[[0.10499359 0.19661193 0.25       0.19661193 0.10499359]
 [0.04517666 0.04517666 0.23500371 0.23500371 0.25      ]]


## Mock Neural Network
Forward pass we perform: $$A^{[0]} = X \leftarrow \text{input layer}\\
Z^{[1]} = W^{[1]}A^{[0]} + b^{[1]} \\ 
A^{[1]} = g[Z^{[1]}] = \text{ReLU}(Z^{[1]}) \vee \text{Sigmoid}(Z^{[1]}) \\
Z^{[2]} = W^{[2]}A^{[1]} + b^{[2]} \\
A^{[2]} = \text{Softmax}(Z^{[2]})$$

In [ ]:
from Cifar10Loader import Cifar10Loader
from neural_network import NeuralNetwork
from neuron_layer import NeuronLayer
from preprocessor import Preprocessor, PreprocessorAdvanced
from layers.activation_functions import ReLU, Sigmoid
from layers.dropout import Dropout

import numpy as np
np.random.seed(42)

In [7]:
CIFAR_DIR = "..\dataset\cifar10"

loader = Cifar10Loader(CIFAR_DIR)

X_train_raw, y_train = loader.load_train_data()
X_test_raw, y_test = loader.load_test_data()

print(X_train_raw.shape, y_train.shape)

(50000, 3072) (50000,)


In [ ]:
preprocessor = PreprocessorAdvanced()
X_train, y_train, X_val, y_val = preprocessor.preprocess_train_data(X_train_raw, y_train)
X_test, y_test = preprocessor.preprocess_test_data(X_test_raw, y_test)

In [13]:
print('Training: ', X_train.shape, y_train.shape)
print('Validation: ', X_val.shape, y_val.shape)
print('Test: ', X_test.shape, y_test.shape)

Training:  (40000, 3072) (40000,)
Validation:  (10000, 3072) (10000,)
Test:  (10000, 3072) (10000,)


In [10]:
layer_config = [
    {
        'n_inputs': 3072, 
        'n_neurons': 1024, 
        'activation': ReLU(), 
        'dropout': Dropout(0.8)
    },
    {
        'n_inputs': 1024,  
        'n_neurons': 256, 
        'activation': ReLU(), 
        'dropout': None},
    {
        'n_inputs': 256,  
        'n_neurons': 10,  
        'activation': None
    }
]

In [12]:
### Test 1
# Learning rate 0.01
nn = NeuralNetwork(layer_config, learning_rate=0.1)
nn.train(X_train, y_train, X_val, y_val, epochs=100)

Epoch 0, Loss: 2.4959, Validation Accuracy: 0.10
Epoch 10, Loss: 2.1611, Validation Accuracy: 0.25
Epoch 20, Loss: 2.1536, Validation Accuracy: 0.22
Epoch 30, Loss: 2.0812, Validation Accuracy: 0.29
Epoch 40, Loss: 2.0374, Validation Accuracy: 0.23
Epoch 50, Loss: 2.1463, Validation Accuracy: 0.27
Epoch 60, Loss: 1.9198, Validation Accuracy: 0.31
Epoch 70, Loss: 2.0727, Validation Accuracy: 0.25
Epoch 80, Loss: 1.8833, Validation Accuracy: 0.32
Epoch 90, Loss: 1.9385, Validation Accuracy: 0.32


In [ ]:
accuracy = nn.accuracy(X_test, y_test)
print(f"Test accuracy: {accuracy * 100:.2f}%")

Test accuracy: 34.52%
